import type { Metadata } from "next";


import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import LenisScrollProvider from "../../provider/lenis-provider";
import { PlaylistProvider } from "../../contexts/playlist-context";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <LenisScrollProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <PlaylistProvider>{children}</PlaylistProvider>
          </ThemeProvider>
        </LenisScrollProvider>
      </body>
    </html>
  );
}
